# Generated by Django 4.1.2 on 2022-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='vote_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
