# Generated by Django 4.1.2 on 2022-12-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_timechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='vote_time',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timechoice',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
