# Generated by Django 4.1.2 on 2022-12-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_vote_time_alter_timechoice_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timechoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='timechoice',
            name='vote_count',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
