# Generated by Django 4.1.2 on 2022-12-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_timechoice_id_alter_timechoice_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timechoice',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
