# Generated by Django 4.1.2 on 2022-12-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_timechoice_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='vote_time',
        ),
    ]
