# Generated by Django 4.1.2 on 2022-12-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_choice_vote_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timechoice',
            name='time',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timechoice',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
