# Generated by Django 4.1.2 on 2022-12-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_timechoice_id_alter_timechoice_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeChoice',
            new_name='TimeChoices',
        ),
    ]
